// Create User
POST http://localhost:5000/users
Content-Type: application/json

{
    "name": "fathur rohman 123",
    "username": "fathur 123",
    "email": "fathurrohman123@gmail.com",
    "nomorTelepon": "08123456789",
    "password": "123456",
    "confPassword": "123456",
    "role": "promotor"
}


###
// get All Users
GET http://localhost:5000/users

###
// Get single User
GET http://localhost:5000/users/c749b3b0-c7d5-4c20-ac0b-4cc363da9cb3
###
// Update User
PATCH  http://localhost:5000/users/6fd22e07-9812-4da2-b0ac-0325fa6140d3
Content-Type: application/json

{
    "name": "Makmum versi lima",
    "email": "makmum123@gmail.com",
    "password": "",
    "confPassword": "",
    "role": "user"
}

###
// delete a user
DELETE http://localhost:5000/users/cc113b1c-5073-4f3f-9cd4-8be3c4d63be0

###
// Login User
POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "admin@gmail.com",
    "password": "123456"
    
}

###
POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "makmum123@gmail.com",
    "password": "123456"
    
}

###
// Me
GET http://localhost:5000/me

###
// Logout User
DELETE  http://localhost:5000/logout

###
// Get All Events
GET http://localhost:5000/events

###
// Get Single Events
GET http://localhost:5000/events/5c1110dc-492e-4520-bdc2-2037b5f1a16f


###
// POST Data Events
POST http://localhost:5000/events
Content-Type: application/json

{
    "name": "Event Konser For Revenge 2024",
    "price": "10000",
    "promotor": "JadiinAjaDulu",
    "lokasi": "batam",
    "tanggal": "21-12-2024",
    "quantity": "1000"
    
}

###
// Update Data Events
PATCH http://localhost:5000/events/b03e1a1c-3665-4f47-9439-ac8d17a146c2
Content-Type: application/json

{
    "name": "Event Konser ColdPlay 123",
    "price": "300000",
    "promotor": "YangMahaKuasa",
    "lokasi": "Batam, Kepulauan Riau",
    "tanggal": "20-05-2023"
    
}

###
// delete a Events
DELETE http://localhost:5000/events/1b84ffc9-8256-4549-b330-93579f5e4014


###
// Get all Volunteers
GET http://localhost:5000/volunteers

###
// Get Single Volunteers
GET http://localhost:5000/volunteers/332d59d9-b763-48bb-a076-0ad49cab9a55

###
// Post Data Volunteers
POST http://localhost:5000/volunteers
Content-Type: application/json

{
    "name": "Volunteer alditaher",
    "price": "00000",
    "promotor": "Bismillah Sukses",
    "lokasi": "bandung",
    "tanggal": "21-12-2023"
    
}


###
// Update Data Volunteers
PATCH http://localhost:5000/volunteers/83f916e2-0a2c-4df1-b112-23c33659ff74
Content-Type: application/json

{
    "name": "Volunteer Kolpley 3 hari",
    "price": "300000",
    "promotor": "Bismillah mantap",
    "lokasi": "Batam, Kepulauan Riau",
    "tanggal": "20-05-2023"
    
}


###
// Delete Data Volunteers
DELETE http://localhost:5000/volunteers/83f916e2-0a2c-4df1-b112-23c33659ff74


###
// Get all Ticket
GET http://localhost:5000/ticket
Content-Type: application/json


###
// Get Single Ticket
GET http://localhost:5000/ticket/7de98d90-30a0-45c0-bb5b-ca5c2d9b4dc8
Content-Type: application/json


###
// create Ticket
POST  http://localhost:5000/events/7cc40917-b8a3-407a-aa65-2689c20129ce/pemesanan/88994/ticket
Content-Type: application/json


###
// update Ticket
PATCH   http://localhost:5000/events/7cc40917-b8a3-407a-aa65-2689c20129ce/pemesanan/88994/ticket/7de98d90-30a0-45c0-bb5b-ca5c2d9b4dc8

Content-Type: application/json

{
    "jumlahTicket": "5"
    
}



###
// Delete Ticket
DELETE   http://localhost:5000/events/7cc40917-b8a3-407a-aa65-2689c20129ce/ticket/7de98d90-30a0-45c0-bb5b-ca5c2d9b4dc8
Content-Type: application/json



###
// Get all pemesanan
GET http://localhost:5000/pemesanan
Content-Type: application/json

###
// Get Single pemesanan
GET http://localhost:5000/pemesanan/88993
Content-Type: application/json

###
// create Pemesanan
POST  http://localhost:5000/events/7cc40917-b8a3-407a-aa65-2689c20129ce/pemesanan
Content-Type: application/json

{
    "jumlahTicket": "3"
}

###
// Update Pemesanan
PATCH  http://localhost:5000/pemesanan/88994
Content-Type: application/json

{
    "jumlahTicket": "6"
}

###
// Delete Pemesanan
DELETE   http://localhost:5000/pemesanan/88994
Content-Type: application/json